### ISSUE TITLE
Build failed 

### ISSUE THREAD

**Issue by thewhiterabbit** [nutti/UE4-Noise-BlueprintLibrary#1]
I copied the NoiseBlueprintLibrary folder to the UE4 project plugins directory, then I opened VS2019 and created project from existing and used the NoiseBlueprintLibrary folder as the source.

This error get:

```
1>------ Build started: Project: NoiseBlueprintLibrary, Configuration: Debug x86 ------
1>C:\Users\ethan\Documents\Unreal Projects\Driven_to_Survive\Plugins\NoiseBlueprintLibrary\Source\NoiseBlueprintLibrary\NoiseBlueprintLibrary.Build.cs(3,7,3,22): error CS0246: The type or namespace name 'UnrealBuildTool' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\ethan\Documents\Unreal Projects\Driven_to_Survive\Plugins\NoiseBlueprintLibrary\Source\NoiseBlueprintLibrary\NoiseBlueprintLibrary.Build.cs(5,38,5,49): error CS0246: The type or namespace name 'ModuleRules' could not be found (are you missing a using directive or an assembly reference?)
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

I tried to build from inside UE4 and got generic error "Driven_to_Survive could not be compiled. Try rebuilding from source manually."

**Comment by nutti** [comment]
@thewhiterabbit 

Could you give me more detail information?
In my environment (UE4 4.25, VS2019), the plugin seems to be built successfully.

**Comment by nutti** [comment]
@thewhiterabbit 

Is there any update?

**Comment by nutti** [comment]
I will close this issue for now.

@thewhiterabbit 
If you have still problem, please reopen this issue.
